
[services]

  [services.add]

    [services.add.debug]
      port = 3000
      url = ""

    [services.add.grpc]
      port = 2000
      url = ""

    [services.add.http]
      port = 8000
      url = ""
